:spring_boot_version: 2.2.1.RELEASE
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-relational-data-access

Accessing relational data with Spring.

The simple data access logic you will work with manages the first and last names of
customers.

== Store and Retrieve Data

This `Application` class implements Spring Boot's `CommandLineRunner`.

First, install some DDL by using the `execute` method of `JdbcTemplate`.

Second, take a list of strings and, by using Java 8 streams, split them into
firstname/lastname pairs in a Java array.

Then install some records in your newly created table by using the `batchUpdate` method of
`JdbcTemplate`. The first argument to the method call is the query string. The last
argument (the array of `Object` instances) holds the variables to be substituted into the
query where the `?` characters are.

Finally, use the `query` method to search your table for records that match the criteria.
You again use the `?` arguments to create parameters for the query, passing in the actual
values when you make the call. The last argument is a Java 8 lambda that is used to
convert each result row into a new `Customer` object.

You should see the following output:

====
[source,bash]
----
2019-12-06 21:56:46.490  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Creating tables
2019-12-06 21:56:46.492  INFO 6260 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-12-06 21:56:46.674  INFO 6260 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for John Woo
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for Jeff Dean
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for Josh Bloch
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for Josh Long
2019-12-06 21:56:46.713  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Querying for customer records where first name = 'Josh':
2019-12-06 21:56:46.724  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Customer[id = 3, firstName = 'Josh', lastName = 'Bloch']
2019-12-06 21:56:46.724  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Customer[id = 4, firstName = 'Josh', lastName = 'Long']
2019-12-06 21:56:46.726  INFO 6260 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-12-06 21:56:46.727  INFO 6260 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
----
====
