:spring_boot_version: 2.2.1.RELEASE
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-relational-data-access

Project made by following the Spring guide.

Accessing relational data with Spring.

In this simple data access logic I worked with manages the first and last names of
customers.

== Store and Retrieve Data

This `Application` class implements Spring Boot's `CommandLineRunner`.

First, I used the `execute` method of `JdbcTemplate`.

Second, I took a list of strings and split them into firstname/lastname pairs in
an array.

Then inserted some records in the table by using the `batchUpdate` method of
`JdbcTemplate`. The first argument to the method call is the query string. The last
argument holds the variables to be substituted into the
query where the `?` characters are.

Finally, used the `query` method to search table for records that match the criteria.
The last argument is a Java 8 lambda that is used to convert each result row into a
new `Customer` object.

Here is the output:

====
[source,bash]
----
2019-12-06 21:56:46.490  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Creating tables
2019-12-06 21:56:46.492  INFO 6260 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2019-12-06 21:56:46.674  INFO 6260 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for John Woo
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for Jeff Dean
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for Josh Bloch
2019-12-06 21:56:46.695  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Inserting customer record for Josh Long
2019-12-06 21:56:46.713  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Querying for customer records where first name = 'Josh':
2019-12-06 21:56:46.724  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Customer[id = 3, firstName = 'Josh', lastName = 'Bloch']
2019-12-06 21:56:46.724  INFO 6260 --- [           main] c.e.r.RelationalDataAccessApplication    : Customer[id = 4, firstName = 'Josh', lastName = 'Long']
2019-12-06 21:56:46.726  INFO 6260 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-12-06 21:56:46.727  INFO 6260 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
----
====
